### ISSUE TITLE
Installing cellpylib

### ISSUE THREAD

**Issue by Mmark94** [lantunes/cellpylib#1]
Hi, how can I install cellpylib?

**Comment by lantunes** [comment]
Hi, 
I have updated the project so that it now contains a `setup.py` file. You should be able to install with pip, using:
```
pip install git+https://github.com/lantunes/cellpylib.git
```

Thanks,
Luis

**Comment by lantunes** [comment]
I have uploaded the package to PyPi, and it can now be installed with:
```
pip install cellpylib
```
I have also updated the `README` file.

Thanks,
Luis

**Comment by Mmark94** [comment]
Thanks a lot. It is working now

Il giorno dom 10 mar 2019 alle ore 14:35 Luis Antunes <
notifications@github.com> ha scritto:
