### ISSUE TITLE
[JOSS] Documentation issues

### ISSUE THREAD

**Issue by szhorvat** [lantunes/cellpylib#10]
The documentation of certain functions is in my opinion insufficiently detailed. There are a number of functions implementing concepts that I was not familiar with. The documentation does not explain these concepts. Instead, it simply references some papers or arXiv preprints. I feel that having to read a paper to understand what a function does is too big an ask, especially when the function can be implemented in less than 10 lines.

I think that all functions in `bien.py` could benefit from better documentation, and a brief explanation of what is being calculated.

**Comment by szhorvat** [comment]
It should be made explicit that entropy results (such as from `shannon_entropy`) are expressed in base 2.

**Comment by szhorvat** [comment]
`plot2d_spacetime` and `plot2d_slice` need docstrings.

**Comment by lantunes** [comment]
@szhorvat I have added more documentation to the functions in `entropy.py` and `bien.py`, as well as to the functions `plot2d_slice` and `plot2d_animate`. The changes are on the `joss_review` branch.

**Comment by szhorvat** [comment]
I find this description a bit awkward:

> `bits_to_int(bits)` Converts a binary array representing bits into the corresponding int in base 10

An `int` is not in any base. We cannot say that "it is in base 10". Only a list of digits has a base, not a number.

**Comment by lantunes** [comment]
I have updated the `bits_to_int` docstring. It now reads:
```
Converts a binary array representing a binary number into the corresponding int.
:param bits: a list of 1s and 0s, representing a binary number
:return: and int representing the corresponding number
```
The relevant commit is f774faac6613f650dfa8614ab084704a133ea6a4.
