### ISSUE TITLE
[JOSS] Wishlist: Colormap support and feature parity for plotting functions

### ISSUE THREAD

**Issue by szhorvat** [lantunes/cellpylib#12]
As far as I can tell, `plot2d_animate` is the only plotting function that has colormap support.  With cellular automata that operate with a small and fixed number of discrete states, it is very useful to be able to assign a specific colour to each state. Thus, it would be nice to have this feature for all plotting functions, both for the 1D and 2D cases.

I notice that `plot2d_animate` has a bunch of other visualization settings that could also be ported to other plotting functions, such as `show_grid`.

**Comment by lantunes** [comment]
@szhorvat Thank you for pointing out these issues. I have added colormap support to the other plotting functions. I have also added `show_grid`, and other arguments, to the other "plot2d" functions. These changes are on the `joss_review` branch, and the relevant commits are 3f1861a94ac9ceff14341b501ab3a9ca88b031c8 and 067fae480434f3fadde9433f2301945bf0af6ca9.
