### ISSUE TITLE
[JOSS] Changelog is not available

### ISSUE THREAD

**Issue by szhorvat** [lantunes/cellpylib#14]
The past releases do not provide a changelog, see https://github.com/lantunes/cellpylib/releases

If this software is to be relied upon by researchers, I strongly suggest to start providing changelogs going forward (or even back to version 1.0.0, which I assume marks the beginning of a stable API?).

On a related note, does versioning follow semver? If yes, it is useful to mention this.

**Comment by lantunes** [comment]
I have added a changelog in the `joss_review` branch. It clarifies that the project adheres to semver.

**Comment by lantunes** [comment]
For reference, the relevant commit is 0b30427cd4e6257aae5d6f3af96d133352eafb9f.
