### ISSUE TITLE
[JOSS] Update copyright section of README

### ISSUE THREAD

**Issue by blsqr** [lantunes/cellpylib#15]
In the Copyright section of the README you currently state "All rights reserved". I am not a lawyer, but in the context of Open Source Software this may introduce some confusion because the phrase appears to be [obsolete](https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence) (for the purpose of establishing copyright) and you license the software under the Apache license anyway, somewhat contradicting the statement.

Propositions:
* *If* you are fine with it, remove the "All rights reserved" phrase
* Update the year in the copyright notice
* Somewhere in the README mention that cellpylib is open source software and refer to the license file

**Comment by lantunes** [comment]
I have replaced the copyright statement in the README with a link to the Apache 2.0 License. This change is on the `joss_review` branch.

**Comment by blsqr** [comment]
As a brief follow-up question to 44b7e8f: did you intend to remove the copyright notice altogether?

To clarify: I did not want to suggest that the Copyright notice itself should be removed, only the "all rights reserved" phrase. While there need not necessarily be a copyright statement to establish copyright, afaik, it still seems to be commonplace to have one. Either way is fine for me, just wanted to make you aware of that.
