### ISSUE TITLE
[JOSS] Use `__call__` magic method for rule classes

### ISSUE THREAD

**Issue by blsqr** [lantunes/cellpylib#18]
A suggestion that would make the use of rule classes like [`ReversibleRule`](https://github.com/lantunes/cellpylib/blob/master/cellpylib/ca_functions.py#L229) more concise: Implement a `__call__` magic method, such that the following syntax becomes possible:

```python
ca = cpl.init_random(200)
my_rule = cpl.ReversibleRule(ca[0], 90)

ca = cpl.evolve(ca, timesteps=100, apply_rule=my_rule)  # NOTE: Without .apply_rule
```

Implementation would be:

```python
class ReversibleRule:
    def __init__(self, init_state, rule_number):
        self._previous_state = init_state
        self._rule_number = rule_number

    def __call__(self, n, c, t):
        regular_result = nks_rule(n, self._rule_number)
        new_result = regular_result ^ self._previous_state[c]
        self._previous_state[c] = n[len(n) // 2]

        return new_result
```

In my mind, this not only simplifies the interface but also represents a clearer model of what a rule is: a *callable* that propagates the CA state.

Two further suggestions in that context:
* I would propose to add a section to the docs, perhaps under "additional features" that illustrates how to implement a stateful rule like the `ReversibleRule`, such that users of CellPyLib can themselves define more advanced rules.
* In case you intend to go towards more complex rule classes, you could consider providing a `BaseRule` class from which users can derive their own rule implementations. Such a base class may provide the interface (abstract `__call__` method) and provide a template for expansion.

What do you think?

**Comment by lantunes** [comment]
For reference, the relevant commit is 8a950ba832b22d62c632abc2ce3b5b192c1e3dfb.
