### ISSUE TITLE
[JOSS] Plotting-related questions and suggestions

### ISSUE THREAD

**Issue by blsqr** [lantunes/cellpylib#20]
I'm unsure how expansive the plotting functionality of this package is meant to be and what its aim is. For instance, is it meant to be used for producing publication-ready plots? Or rather as a set of useful functions during the exploratory phase of a CA?
Can you briefly comment on that, @lantunes?

Expanding on #12, I have a few suggestions regarding the plotting functionality of cellpylib; depending on your comment to the above, these may or may not apply.

---

### 1 - Pass on arguments to underlying plotting function
This would make the plotting functions much more flexible, as it allows to pass on arguments to `plt.imshow`:

```python
def plot(ca, title='', *, cmap='Greys', **imshow_kwargs):
    plt.title(title)
    plt.imshow(ca, interpolation='none', cmap=cmap, **imshow_kwargs)
    plt.show()
```
While not super relevant for the (short) `plot` function, larger functions like `plot2d_animate` would benefit from that, imo.

### 2 - Allow for non-interactive use (or document that this is not possible)
Afais, all plot functions end in `plt.show()`. If called in a script (like those in `demos/`), this leads to the interactive matplotlib window appearing, requiring user interaction.

This prohibits automation for *saving* plots, because the appearing plot windows need to be manually closed for the script to continue running. Example scenario: Making a bunch of different instantiations of a stochastic CA and their evolution and intending to save all of the resulting plots or animations.

I see the appeal of the current implementation of the plot function, especially when interactively working with the library. However, I think the plots *always* being shown unnecessarily restricts the plotting functions to these interactive use cases.

Proposition: Add another keyword argument (`show=True`) which can be set to `False` if working non-interactively. Alternatively, add a module-level variable that controls the default behaviour (but this is a tad more complicated to coordinate, probably overkill).

**Comment by lantunes** [comment]
@blsqr Thank you for this very useful feedback! The plotting functions were generally meant to be used for immediate, exploratory purposes only, but there is no reason why they couldn't be changed to allow users to add more customization for publication purposes.

I have made the changes, **1** and **2**, that you describe, on the `joss_review` branch. The relevant commits are 3f1861a94ac9ceff14341b501ab3a9ca88b031c8 and 4562162040ed35f5c065079022a5ee6d553cec91.
