### ISSUE TITLE
[JOSS] Report (and improve) test coverage

### ISSUE THREAD

**Issue by blsqr** [lantunes/cellpylib#21]
Running `python -m pytest tests/ --cov=cellpylib` (with `pytest-cov` package installed) currently yields the following coverage report:

```
---------- coverage: platform darwin, python 3.9.6-final-0 -----------
Name                          Stmts   Miss  Cover
-------------------------------------------------
cellpylib/__init__.py             9      0   100%
cellpylib/apen.py                17      1    94%
cellpylib/bien.py                45      0   100%
cellpylib/ca_functions.py       133     17    87%
cellpylib/ca_functions2d.py     119     69    42%
cellpylib/ctrbl_rule.py          27      0   100%
cellpylib/entropy.py             35      1    97%
cellpylib/hopfield_net.py        28      0   100%
cellpylib/langtons_loop.py      121    116     4%
cellpylib/rule_tables.py         74      6    92%
-------------------------------------------------
TOTAL                           608    210    65%
```

Wide parts of the library seem to be well-covered and most of the missing statements come from the (rather complicated) `langtons_loop` module. However, I would expect a higher test coverage in the two `ca_functions` modules, given that they are the core part of the library.

@lantunes Have you checked which of the statements are currently untested and would you consider expanding the corresponding tests to cover wider parts of the core library?

**Comment by lantunes** [comment]
@blsqr I have added more test coverage in the `joss_review` branch. The majority of the untested code now consists of the "plot" functions, such as `plot2d` in `ca_functions2d.py`. I haven't yet thought of a worthwhile approach for testing these kinds of functions.

**Comment by blsqr** [comment]
Sounds good 👍 

Regarding the plot functions, there appears to be some overlap to points raised in #20, specifically that of `plt.show()` prohibiting testing. I found this [SO answer](https://stackoverflow.com/a/26974098/1827608) detailing how the interactive mode can be turned off – this would allow *coverage* tests of the plot functions. Maybe worth experimenting?

Of course testing whether the plot output matches the expectations is not feasible. Nevertheless, I personally find it beneficial for Python code to have coverage tests for matplotlib code, e.g. to make sure that (given some input) the functions run through.

**Comment by lantunes** [comment]
@blsqr I have added some coverage tests for the plotting code, in the `joss_review` branch. The coverage is now 98%.

**Comment by blsqr** [comment]
Very nice 👍 

What do you think about opening a Draft PR for that branch, such that we can more easily track which issues are addressed by it?

**Comment by lantunes** [comment]
I have opened a draft PR here: https://github.com/lantunes/cellpylib/pull/23.
