### ISSUE TITLE
[JOSS] Use of deprecated `np.int`

### ISSUE THREAD

**Issue by blsqr** [lantunes/cellpylib#22]
Running the tests emits a large number (>600) of warnings, most of which stem from the use of `np.int` in the `init_…` functions. `np.int` is simply an alias to the builtin Python `int` and – as of numpy 1.20 – `np.int` is [deprecated](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).

You can simply replace it with `int` to address the warnings. Alternatively, you may want to use the precision limited (but perhaps faster) `np.int64`, `np.int32`…

**Comment by lantunes** [comment]
Thanks @blsqr! I have made some changes to address the warnings emitted while running the tests. I no longer see any warnings. The changes are in the `joss_review` branch, and this issue will be closed when that branch is merged into `master`.

**Comment by blsqr** [comment]
Perfect! 👍
