### ISSUE TITLE
Evolve should accept CA with prior history

### ISSUE THREAD

**Issue by lantunes** [lantunes/cellpylib#25]
Currently, the `evolve` and `evolve2d` functions assume the initial conditions consist of just the first timestep, and start from the first (and only) state of the given initial conditions list. However, it would be convenient if a user could supply a list of multiple states, representing some prior evolution history, and the `evolve` and `evolve2d` functions could continue from the last state in the list.

**Comment by szhorvat** [comment]
I guess this can be closed now too? Thanks for implementing this!

**Comment by lantunes** [comment]
Yes, and thanks for all your suggestions and feedback!
