### ISSUE TITLE
Plotting animation issue in Spyder IDE

### ISSUE THREAD

**Issue by moijn001** [lantunes/cellpylib#29]
Plotting the animations from CPL in Spyder IDE does not work for me.  Using **cpl.plot2d_animate()**

The issue I get:
> UserWarning: Animation was deleted without rendering anything. This is most likely unintended. To prevent deletion, assign the Animation to a variable that exists for as long as you need the Animation.
  warnings.warn(

Relates to these issues:  

- https://stackoverflow.com/questions/68956448/matplotlib-funcanimation-step-by-step-animation-function
- https://issueexplorer.com/issue/matplotlib/matplotlib/21007
- https://stackoverflow.com/questions/35856079/animation-from-matplotlib-not-working-in-spyder

I can get other animations to work, such as matplotlib simple animation: https://matplotlib.org/2.0.2/examples/animation/simple_anim.html

Perhaps there is something in the cpl.plot2d_animate function that is missing or should be returning an object?

Code used:

`    # Glider
    cellular_automaton = cpl.init_simple2d(60, 60)
    cellular_automaton[:, [28,29,30,30], [30,31,29,31]] = 1   
    
    # evolve the cellular automaton for 60 time steps
    cellular_automaton = cpl.evolve2d(cellular_automaton, timesteps=60, neighbourhood='Moore',
                                      apply_rule=cpl.game_of_life_rule, memoize='recursive')
    
    # None of these matplotlib commands really solve the issue:
    # %matplotlib qt5
    # %matplotlib qt4
    # %matplotlib inline

    anim = cpl.plot2d_animate(cellular_automaton, interval=50, save=False)`

**Comment by lantunes** [comment]
Thanks for reporting this error. I was able to reproduce this problem. I found that if I return the animation from the `plot2d_animate` function, and assign it to a variable, as you have done in your example, it works. I will update the code and issue a new release shortly.

**Comment by lantunes** [comment]
I have released `v2.3.1`, which should address this problem. Please update your version of cellpylib, and try again. Let me know if it resolves your problem, and I will update this issue accordingly. Thanks!

**Comment by moijn001** [comment]
Thanks Lantunes! The animation now opens in a Matplotlib window and animates correctly!   Super awesome!

Small note: It's still necessary to save the output from the '`cpl.plot2d_animate`' function into a variable to get the animation. Might be a good addition to the README examples, or just a comment on the side for Spyder users.

```
#This animation works:   
anim =  cpl.plot2d_animate(cellular_automaton, interval=5, save=False) 

#This gives a freezed frame (no animation)
cpl.plot2d_animate(cellular_automaton, interval=5, save=False)
```

**Comment by moijn001** [comment]
Issue sucessfully solved.  Closing the issue

**Comment by lantunes** [comment]
Thanks @moijn001! I will look to add a note in the documentation.
