### ISSUE TITLE
[JOSS] Minor tweaks to references in paper.md

### ISSUE THREAD

**Issue by blsqr** [lantunes/cellpylib#7]
Hi @lantunes, I'm here as one of the reviewers from your [submission to JOSS](https://github.com/openjournals/joss-reviews/issues/3608) 👋 

I just read the paper (before looking into the code) and have only minor remarks regarding the references:

1) In the first paragraph, the two successive citations can be combined like this:

```
... Deep Learning [@nichele2017deep,@mordvintsev2020growing] ...
```

2) I think it would be more appropriate to mark up the title of the Wolfram book as italic (as done in the references) rather than verbatim. Just a suggestion, though.

3) For the Mordvintsev et al. citation, they supply the following BibTeX on their webpage, which includes a DOI (that @whedon must have missed):

```
@article{mordvintsev2020growing,
  author = {Mordvintsev, Alexander and Randazzo, Ettore and Niklasson, Eyvind and Levin, Michael},
  title = {Growing Neural Cellular Automata},
  journal = {Distill},
  year = {2020},
  note = {https://distill.pub/2020/growing-ca},
  doi = {10.23915/distill.00023}
}
```

4) Did you check if there are DOIs available for the Wolfram and von Neumann books? (There sometimes are, but if not, no worries.)

Let me know if there are questions or if I can assist with anything.

**Comment by lantunes** [comment]
Hi @blsqr,

Thank you for your review! I have pushed some changes directly to `master` which should address the items you mention. Regarding item 4, I was not able to find DOIs for the Wolfram and von Neumann books.

**Comment by blsqr** [comment]
Looking good! I just discovered that the DOI given for the Mordvintsev publication does not appear to work and filed an issue with them [here](https://github.com/distillpub/post--growing-ca/issues/13). Sorry that I didn't check that when proposing to use the BibTeX they provided.

It's a minor issue, so if they don't fix their DOI soon, I'd propose to revert to a citation of the webpage itself. Let's keep this issue open to not forget about it. Is that fine for you as well?

**Comment by blsqr** [comment]
Alright, the DOI issue was fixed in the distill repo, see https://github.com/distillpub/post--growing-ca/issues/13

I think we can close this issue now.

**Comment by lantunes** [comment]
Thanks @blsqr!
