### ISSUE TITLE
[JOSS] Document bits_to_int() and int_to_bits()

### ISSUE THREAD

**Issue by szhorvat** [lantunes/cellpylib#8]
The bits_to_int() and int_to_bits() functions do not have a docstring. Since these are public functions, it would be nice to document them, even if they are fairly trivial.

**Comment by szhorvat** [comment]
Now it is unclear if these were even meant to be public, see #9.

But I do see nice uses for these functions, in case you decide to support them. For example, here's a quick way to create a pseudorandom integer sequence using rule 30:

```
ca30 = cpl.evolve(cpl.init_random(31), 20, apply_rule=lambda n, c, t: cpl.nks_rule(n, 30))
[cpl.bits_to_int(bits) for bits in ca30]
```

**Comment by lantunes** [comment]
@szhorvat Thank you for pointing this out, and for the example outlining how these functions might be used on their own. I have added docs and tests for these functions on the `joss_review` branch.
